In [15]:
import numpy as np
import pandas as pd

In [55]:
url = 'https://www.stoxx.com/document/Indices/Current/HistoricalData/h_vstoxx.txt'
#vstoxx_index = pd.read_csv(url,  sep=';',index_col=0, header=0, parse_dates=True, dayfirst=True)
vstoxx_index = pd.read_csv(url,  sep=',',index_col=0, header=0, parse_dates=True, dayfirst=True)

In [56]:
vstoxx_index.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4359 entries,   to 12.02.2016
Data columns (total 9 columns):
Unnamed: 1    4359 non-null object
Unnamed: 2    3908 non-null object
Unnamed: 3    4359 non-null object
Unnamed: 4    4298 non-null object
Unnamed: 5    4359 non-null object
Unnamed: 6    4359 non-null object
Unnamed: 7    4342 non-null object
Unnamed: 8    4359 non-null object
Unnamed: 9    4345 non-null object
dtypes: object(9)
memory usage: 340.5+ KB

In [57]:
vstoxx_index

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
EURO STOXX 50 Volatility Indices,,,,,,,,,
,VSTOXX,Sub-Index 1M,Sub-Index 2M,Sub-Index 3M,Sub-Index 6M,Sub-Index 9M,Sub-Index 12M,Sub-Index 18M,Sub-Index 24M
Date,V2TX,V6I1,V6I2,V6I3,V6I4,V6I5,V6I6,V6I7,V6I8
04.01.1999,18.2033,21.2458,17.5555,31.2179,33.3124,33.7327,33.2232,31.8535,23.8209
05.01.1999,29.6912,36.6400,28.4274,32.6922,33.7326,33.1724,32.8457,32.2904,25.0532
06.01.1999,25.1670,25.4107,25.1351,32.2186,32.6459,31.9673,32.9260,33.2871,26.0107
...,...,...,...,...,...,...,...,...,...
08.02.2016,33.3917,34.7251,33.2189,31.8308,31.4783,30.6941,30.3705,29.8478,29.2559
09.02.2016,33.9664,35.7884,33.7800,32.6220,32.2459,31.5572,31.1659,30.5339,29.9000
10.02.2016,33.4528,34.6020,33.3637,32.1438,32.0018,31.2099,30.9937,30.8174,30.2533
11.02.2016,38.3051,41.2095,38.1347,35.8676,35.1073,33.7847,33.4126,32.2234,31.2124
12.02.2016,35.6846,35.3849,35.6965,34.1404,33.8645,32.9590,32.8208,32.3189,31.8194

In [51]:
#vstoxx_index =vstoxx_index[('2020-01-04' < vstoxx_index.index) & (vstoxx_index.index < '2020-02-16')]

In [58]:
#vstoxx_index

In [59]:
np.round(vstoxx_index.tail(), 2)

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
EURO STOXX 50 Volatility Indices,,,,,,,,,
08.02.2016,33.3917,34.7251,33.2189,31.8308,31.4783,30.6941,30.3705,29.8478,29.2559
09.02.2016,33.9664,35.7884,33.7800,32.6220,32.2459,31.5572,31.1659,30.5339,29.9000
10.02.2016,33.4528,34.6020,33.3637,32.1438,32.0018,31.2099,30.9937,30.8174,30.2533
11.02.2016,38.3051,41.2095,38.1347,35.8676,35.1073,33.7847,33.4126,32.2234,31.2124
12.02.2016,35.6846,35.3849,35.6965,34.1404,33.8645,32.9590,32.8208,32.3189,31.8194